# Generated by Django 2.2.5 on 2019-11-08 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities_light', '0008_city_timezone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(null=True)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('occupation', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=25, unique=True)),
                ('avatar', models.ImageField(null=True, upload_to='communities/avatars')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default='Name', max_length=25)),
                ('last_name', models.CharField(blank=True, default='Surname', max_length=25)),
                ('full_name', models.CharField(blank=True, max_length=51)),
                ('avatar', models.ImageField(null=True, upload_to='profiles/avatars')),
                ('header', models.ImageField(null=True, upload_to='profiles/headers')),
                ('status', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.TextField(blank=True)),
                ('about', models.TextField(blank=True)),
                ('shows', models.TextField(blank=True)),
                ('bands', models.TextField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('dribbble', models.URLField(blank=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='people', to='cities_light.City')),
                ('communities', models.ManyToManyField(related_name='members', to='api.Community')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='people', to='cities_light.Country')),
                ('followers', models.ManyToManyField(to='api.Profile')),
                ('friends', models.ManyToManyField(related_name='_profile_friends_+', to='api.Profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(null=True)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replys', to='api.Profile')),
                ('comment_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='api.Comment')),
                ('liked_by', models.ManyToManyField(related_name='liked_replys', to='api.Profile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('likes', models.PositiveIntegerField(default=0)),
                ('reposts', models.PositiveIntegerField(default=0)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='api.Profile')),
                ('liked_by', models.ManyToManyField(related_name='liked_posts', to='api.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cities_light.City')),
                ('country', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cities_light.Country')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.Profile'),
        ),
        migrations.AddField(
            model_name='comment',
            name='liked_by',
            field=models.ManyToManyField(related_name='liked_comments', to='api.Profile'),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.Post'),
        ),
    ]
