# Generated by Django 2.1.7 on 2019-04-22 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190421_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='residence',
            name='region',
        ),
    ]
