# Generated by Django 2.2.1 on 2019-06-04 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190604_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='intro',
        ),
        migrations.AddField(
            model_name='profile',
            name='about',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='bands',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='dribbble',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='profile',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='shows',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='website',
            field=models.TextField(blank=True),
        ),
    ]
