# Generated by Django 2.1.7 on 2019-04-24 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190424_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='/avatars/billie.jpg', upload_to='avatars'),
        ),
    ]
