# Generated by Django 2.1.7 on 2019-05-03 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20190424_1930'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendshipRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(choices=[('REQUESTED', 'requested'), ('ACCEPTED', 'accepted'), ('REJECTED', 'rejected')], default='REQUESTED')),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='friends',
        ),
        migrations.AddField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(through='api.FriendshipRequest', to='api.Profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='friendshiprequest',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='api.Profile'),
        ),
        migrations.AddField(
            model_name='friendshiprequest',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='api.Profile'),
        ),
    ]
