# Generated by Django 2.1.7 on 2019-05-07 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20190504_1712'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FriendshipRequest',
            new_name='Friendship',
        ),
        migrations.AddField(
            model_name='profile',
            name='followers',
            field=models.ManyToManyField(to='api.Profile'),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='friends',
        ),
        migrations.AddField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(to='api.Profile'),
        ),
    ]
