# Generated by Django 2.2.1 on 2019-05-13 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20190513_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reposts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
