# Generated by Django 2.2.1 on 2019-05-14 20:56

from django.db import migrations, models
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20190513_2316'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileIntro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shows', models.TextField(blank=True)),
                ('about', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='intro',
            field=picklefield.fields.PickledObjectField(editable=False, null=True),
        ),
    ]
