# Generated by Django 2.2.1 on 2019-05-21 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20190514_2356'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileIntro',
        ),
    ]
