# Generated by Django 2.2.1 on 2019-05-21 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_delete_profileintro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('occupation', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=25, unique=True)),
                ('avatar', models.ImageField(default='communities/avatars/default.jpg', upload_to='communities/avatars')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='favourite_pages',
            field=models.ManyToManyField(related_name='members', to='api.Community'),
        ),
    ]
