# Generated by Django 2.2.1 on 2019-05-21 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_auto_20190521_1542'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='favourite_pages',
            new_name='communities',
        ),
    ]
