# Generated by Django 2.2.1 on 2019-06-03 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_post_liked_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='community',
            old_name='address',
            new_name='url',
        ),
        migrations.AlterField(
            model_name='community',
            name='avatar',
            field=models.ImageField(null=True, upload_to='communities/avatars'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(null=True, upload_to='profiles/avatars'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='header',
            field=models.ImageField(null=True, upload_to='profiles/headers'),
        ),
    ]
